export default [
  {
    id: 1,
    key: 'es',
    text: 'Escalade',
    value: '1',
    image: '/img/escalade.png',
    image_color: '/img/escalade_color.png',
    bg: '/img/escalade_bg.jpg',
    color: '#ff8f3f',
  },
  {
    id: 2,
    key: 'ru',
    text: 'Running',
    value: '2',
    image: '/img/running.png',
    image_color: '/img/running_color.png',
    bg: '/img/running_bg.jpg',
    color: '#6B184E',
  },
  {
    id: 3,
    key: 'cy',
    text: 'Cyclisme',
    value: '3',
    image: '/img/cyclisme.png',
    image_color: '/img/cyclisme_color.png',
    bg: '/img/velo_bg.jpg',
    color: '#aabb22',
  },
  {
    id: 4,
    key: 'gm',
    text: 'Sports de glisse - MER',
    value: '4',
    image: '/img/glisse_mer.png',
    image_color: '/img/glisse_mer_color.png',
    bg: '/img/glisse_mer_bg.jpg',
    color: '#0D8BBB',
  },
  {
    id: 5,
    key: 'go',
    text: 'Sports de glisse - MONTAGNE',
    value: '5',
    image: '/img/glisse_montagne.png',
    image_color: '/img/glisse_montagne_color.png',
    bg: '/img/glisse_montagne_bg.jpg',
    color: '#ff8f3f',
  },
  {
    id: 6,
    key: 'gu',
    text: 'Sports de glisse - URBAIN',
    value: '6',
    image: '/img/glisse_urbain.png',
    image_color: '/img/glisse_urbain_color.png',
    bg: '/img/glisse_urbain_bg.jpg',
    color: '#6B184E',
  },
  {
    id: 7,
    key: 'ra',
    text: 'Randonnée',
    value: '7',
    image: '/img/rando.png',
    image_color: '/img/rando_color.png',
    bg: '/img/rando_bg.jpg',
    color: '#aabb22',
  },
  {
    id: 8,
    key: 'vt',
    text: 'VTT',
    value: '8',
    image: '/img/vtt.png',
    image_color: '/img/vtt_color.png',
    bg: '/img/vtt_bg.jpg',
    color: '#ff8f3f',
  },
  {
    id: 9,
    key: 'fi',
    text: 'Fitness',
    value: '9',
    image: '/img/fitness.png',
    image_color: '/img/fitness_color.png',
    bg: '/img/fitness_bg.jpg',
    color: '#6B184E',
  },
  {
    id: 10,
    key: 'na',
    text: 'Natation',
    value: '10',
    image: '/img/natation.png',
    image_color: '/img/natation_color.png',
    bg: '/img/natation_bg.jpg',
    color: '#0D8BBB',
  },
  {
    id: 11,
    key: 'yo',
    text: 'Yoga',
    value: '11',
    image: '/img/yoga.png',
    image_color: '/img/yoga_color.png',
    bg: '/img/yoga_bg.jpg',
    color: '#6B184E',
  },
  {
    id: 12,
    key: 'au',
    text: 'Autre sport',
    value: '12',
    image: '/img/autre.png',
    image_color: '/img/autre_color.png',
    bg: '/img/autre_bg.jpg',
    color: '#CF2B6B',
  },

];
